<a href="https://colab.research.google.com/github/sahilchavan08/Machine_Larnining/blob/main/Market_Basket_Analysis_Association_Rule_Mining_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Market Basket Analysis

In [1]:
# INSTALL APYORI PACKAGE

In [2]:
pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5996 sha256=d007f90210a8f8f90dcccb62d19829e50570cec0e853c6f3d3535aa9cf881a64
  Stored in directory: /root/.cache/pip/wheels/4d/9f/d0/7ba4ae3f5de2f76ea362170ea0f157e6cc1d1b9aea188175f2
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

## Restart the cell

In [1]:
## Load the data
import pandas as pd
path = r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/store_data.csv"
df = pd.read_csv(path,header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.shape

(7501, 20)

In [4]:
rows = df.shape[0]
cols = df.shape[1]

In [5]:
df.values[0][0]

'shrimp'

In [6]:
[str(df.values[0,j]) for j in range(cols)]
# df.values[0,0],df.values[0,1],df.values[0,2]....df.values[0,19] 1st row
# df.values[1,0],df.values[1,1],df.values[1,2]....df.values[1,19] 2nd row

['shrimp',
 'almonds',
 'avocado',
 'vegetables mix',
 'green grapes',
 'whole weat flour',
 'yams',
 'cottage cheese',
 'energy drink',
 'tomato juice',
 'low fat yogurt',
 'green tea',
 'honey',
 'salad',
 'mineral water',
 'salmon',
 'antioxydant juice',
 'frozen smoothie',
 'spinach',
 'olive oil']

In [7]:
records = []
for i in range(rows):
  records.append([str(df.values[i,j]) for j in range(cols)])
print(records[:10])

[['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole weat flour', 'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad', 'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie', 'spinach', 'olive oil'], ['burgers', 'meatballs', 'eggs', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['chutney', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['turkey', 'avocado', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['low fat yogurt', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['whole wheat pasta', 'french fries', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['soup', 'light cream', 'shallot', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['frozen vegetables', 'spaghetti', 'green tea', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['french fries', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan']]

In [8]:
rows

7501

  *To build the association rules, we need to build the criteria*

  support : based on data
  confidence : 0.2
  lift : 3

  support : transactions - weekly data: 7days , 5
  support : 7*5/total transactions  = 35/7500

In [9]:

35/len(df)

0.004666044527396347

In [10]:

from apyori import apriori
sup = 7*5/len(df)
conf = 0.2
lift = 3

association_rules = apriori(records,min_support=sup,min_confidence=conf,min_lift=lift)
association_rules = list(association_rules)
print(association_rules[:10])

[RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]), RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]), RelationRecord(items=frozenset({'ground beef', 'herb & pepper'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]), RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]), RelationRecord(items=frozenset({'olive oil', 'whole wheat pasta'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]), RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)]), RelationRecord(items=frozenset({'shrimp', 'frozen vegetables', 'chocolate'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'chocolate'}), items_add=frozenset({'shrimp'}), confidence=0.23255813953488375, lift=3.2545123221103784), OrderedStatistic(items_base=frozenset({'shrimp', 'chocolate'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29629629629629634, lift=3.1084175084175087)]), RelationRecord(items=frozenset({'cooking oil', 'ground beef', 'spaghetti'}), support=0.004799360085321957, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cooking oil', 'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.5714285714285714, lift=3.2819951870487856), OrderedStatistic(items_base=frozenset({'cooking oil', 'spaghetti'}), items_add=frozenset({'ground beef'}), confidence=0.3025210084033613, lift=3.0789824749438446)]), RelationRecord(items=frozenset({'mushroom cream sauce', 'nan', 'escalope'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'nan', 'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049), OrderedStatistic(items_base=frozenset({'mushroom cream sauce', 'nan'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]), RelationRecord(items=frozenset({'nan', 'pasta', 'escalope'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'nan', 'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794), OrderedStatistic(items_base=frozenset({'nan', 'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)])]

In [11]:

len(association_rules)

44

In [12]:

association_rules[0]

RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)])

In [13]:

association_rules[0][0]

frozenset({'escalope', 'mushroom cream sauce'})

In [14]:

association_products = []
for i in association_rules[0][0]:
  association_products.append(i)
print(association_products)

['mushroom cream sauce', 'escalope']

In [15]:
support = association_rules[0][1]
support

0.005732568990801226

In [16]:

association_rules[0][2]

[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]

In [17]:

association_rules[0][2][0]

OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)

In [18]:
print(association_rules[0][2][0][2])
print(association_rules[0][2][0][3])

0.3006993006993007
3.790832696715049

In [19]:
results = []
for items in association_rules:
    #Extract product associations
    item_pair = items[0] #frozen set of items
    item_data = [i for i in item_pair] #save the items in a list

    support1 = items[1] # support

    confidence1 = items[2][0][2]
    lift1 = items[2][0][3]

    results.append([item_data,round(support1,3),round(confidence1,3),round(lift1,2)])
print(results)

[[['mushroom cream sauce', 'escalope'], 0.006, 0.301, 3.79], [['pasta', 'escalope'], 0.006, 0.373, 4.7], [['ground beef', 'herb & pepper'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['olive oil', 'whole wheat pasta'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['shrimp', 'frozen vegetables', 'chocolate'], 0.005, 0.233, 3.25], [['cooking oil', 'ground beef', 'spaghetti'], 0.005, 0.571, 3.28], [['mushroom cream sauce', 'nan', 'escalope'], 0.006, 0.301, 3.79], [['nan', 'pasta', 'escalope'], 0.006, 0.373, 4.7], [['ground beef', 'frozen vegetables', 'spaghetti'], 0.009, 0.311, 3.17], [['frozen vegetables', 'olive oil', 'milk'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['frozen vegetables', 'spaghetti', 'olive oil'], 0.006, 0.206, 3.12], [['frozen vegetables', 'shrimp', 'spaghetti'], 0.006, 0.215, 3.01], [['tomatoes', 'frozen vegetables', 'spaghetti'], 0.007, 0.239, 3.5], [['ground beef', 'grated cheese', 'spaghetti'], 0.005, 0.323, 3.28], [['mineral water', 'ground beef', 'herb & pepper'], 0.007, 0.391, 3.98], [['nan', 'ground beef', 'herb & pepper'], 0.016, 0.323, 3.29], [['ground beef', 'herb & pepper', 'spaghetti'], 0.006, 0.393, 4.0], [['ground beef', 'olive oil', 'milk'], 0.005, 0.224, 3.4], [['tomato sauce', 'nan', 'ground beef'], 0.005, 0.377, 3.84], [['ground beef', 'shrimp', 'spaghetti'], 0.006, 0.523, 3.01], [['milk', 'spaghetti', 'olive oil'], 0.007, 0.203, 3.08], [['soup', 'mineral water', 'olive oil'], 0.005, 0.225, 3.42], [['nan', 'olive oil', 'whole wheat pasta'], 0.008, 0.271, 4.13], [['nan', 'pasta', 'shrimp'], 0.005, 0.322, 4.52], [['olive oil', 'pancakes', 'spaghetti'], 0.005, 0.201, 3.05], [['shrimp', 'nan', 'frozen vegetables', 'chocolate'], 0.005, 0.233, 3.26], [['cooking oil', 'nan', 'ground beef', 'spaghetti'], 0.005, 0.571, 3.28], [['nan', 'ground beef', 'frozen vegetables', 'spaghetti'], 0.009, 0.311, 3.17], [['nan', 'frozen vegetables', 'olive oil', 'milk'], 0.005, 0.203, 3.09], [['nan', 'mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['nan', 'frozen vegetables', 'spaghetti', 'olive oil'], 0.006, 0.206, 3.13], [['nan', 'frozen vegetables', 'shrimp', 'spaghetti'], 0.006, 0.215, 3.02], [['tomatoes', 'nan', 'frozen vegetables', 'spaghetti'], 0.007, 0.239, 3.5], [['nan', 'ground beef', 'grated cheese', 'spaghetti'], 0.005, 0.323, 3.28], [['nan', 'mineral water', 'ground beef', 'herb & pepper'], 0.007, 0.391, 3.98], [['nan', 'ground beef', 'herb & pepper', 'spaghetti'], 0.006, 0.393, 4.0], [['nan', 'ground beef', 'olive oil', 'milk'], 0.005, 0.224, 3.41], [['nan', 'ground beef', 'shrimp', 'spaghetti'], 0.006, 0.523, 3.01], [['nan', 'milk', 'spaghetti', 'olive oil'], 0.007, 0.203, 3.09], [['soup', 'nan', 'mineral water', 'olive oil'], 0.005, 0.225, 3.43], [['nan', 'olive oil', 'pancakes', 'spaghetti'], 0.005, 0.201, 3.06]]

In [20]:
## Save these results inside a dataframe and share with the client
df_results = pd.DataFrame(results)
df_results.head()

                                  0      1      2     3
0  [mushroom cream sauce, escalope]  0.006  0.301  3.79
1                 [pasta, escalope]  0.006  0.373  4.70
2      [ground beef, herb & pepper]  0.016  0.323  3.29
3       [tomato sauce, ground beef]  0.005  0.377  3.84
4    [olive oil, whole wheat pasta]  0.008  0.271  4.12

In [21]:
df_results.columns = ["Product_Associations","Support","Confidence","Lift"]
df_results.head()

               Product_Associations  Support  Confidence  Lift
0  [mushroom cream sauce, escalope]    0.006       0.301  3.79
1                 [pasta, escalope]    0.006       0.373  4.70
2      [ground beef, herb & pepper]    0.016       0.323  3.29
3       [tomato sauce, ground beef]    0.005       0.377  3.84
4    [olive oil, whole wheat pasta]    0.008       0.271  4.12

In [22]:

df_results.to_csv("Product_Associations.csv",index=False)