<a href="https://colab.research.google.com/github/sahilchavan08/Machine_Larnining/blob/main/PCA_Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Principle Component Analysis -> A techique used to eliminate curse of Dimensionality

In [1]:
import pandas as pd
df = pd.read_csv(r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/Cars93.csv",na_values=['NA',''],keep_default_na=False)
df.head()

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

## Perfrom basic data quality checks

In [2]:
df.shape

(93, 28)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  93 non-null     int64
 1   Manufacturer        93 non-null     object
 2   Model               93 non-null     object
 3   Type                93 non-null     object
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             89 non-null     object
 10  DriveTrain          93 non-null     object
 11  Cylinders           93 non-null     object
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     object
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     object
 27  Make                93 non-null     object
dtypes: float64(7), int64(12), object(9)
memory usage: 20.5+ KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                4
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

## Separate X and Y features

In [7]:
X = df.drop(columns=['id','Weight'])
Y = df[['Weight']]

In [8]:
X.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,Front,...,13.2,5,177,102,68,37,26.5,11.0,non-USA,Acura Integra
1,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,18.0,5,195,115,71,38,30.0,15.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,16.9,5,180,102,67,37,28.0,14.0,non-USA,Audi 90
3,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,Front,...,21.1,6,193,106,70,37,31.0,17.0,non-USA,Audi 100
4,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,21.1,4,186,109,69,39,27.0,13.0,non-USA,BMW 535i

In [9]:
Y.head()

   Weight
0    2705
1    3560
2    3375
3    3405
4    3640

In [10]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=21,train_size=0.85)

## Data preprocessing and Data cleaning

In [15]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

cat = list(X.select_dtypes(include='object'))
con = list(X.select_dtypes(include='number'))

num_pipe = make_pipeline(SimpleImputer(strategy='median'),StandardScaler())

cat_pipe = make_pipeline(SimpleImputer(strategy='most_frequent'),OneHotEncoder(handle_unknown='ignore',sparse_output=False))

pre = ColumnTransformer([
    ('cat',cat_pipe,cat),
    ('con',num_pipe,con)
]).set_output(transform='pandas')
pre

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Manufacturer', 'Model', 'Type', 'AirBags',
                                  'DriveTrain', 'Cylinders', 'Man.trans.avail',
                                  'Origin', 'Make']),
                                ('con',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['Min.Price', 'Price', 'Max.Price', 'MPG.city',
                                  'MPG.highway', 'EngineSize', 'Horsepower',
                                  'RPM', 'Rev.per.mile', 'Fuel.tank.capacity',
                                  'Passengers', 'Length', 'Wheelbase', 'Width',
                                  'Turn.circle', 'Rear.seat.room',
                                  'Luggage.room'])])

In [16]:

pre.fit(xtrain)

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Manufacturer', 'Model', 'Type', 'AirBags',
                                  'DriveTrain', 'Cylinders', 'Man.trans.avail',
                                  'Origin', 'Make']),
                                ('con',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['Min.Price', 'Price', 'Max.Price', 'MPG.city',
                                  'MPG.highway', 'EngineSize', 'Horsepower',
                                  'RPM', 'Rev.per.mile', 'Fuel.tank.capacity',
                                  'Passengers', 'Length', 'Wheelbase', 'Width',
                                  'Turn.circle', 'Rear.seat.room',
                                  'Luggage.room'])])

In [17]:

xtrain_pre = pre.transform(xtrain)
xtest_pre = pre.transform(xtest)

In [18]:
xtrain_pre.shape[1]

228

# PCA components

In [19]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pca.fit(xtest_pre)

PCA(n_components=3)

In [20]:
xtrain_pca = pca.transform(xtrain_pre)
xtrain_pca

array([[-5.22071391e+00,  1.04005306e+00,  5.02247226e-01],
       [-2.96683577e+00, -9.51353077e-01, -3.69779408e-01],
       [ 1.57077783e+00,  1.02089773e+00, -8.73815711e-01],
       [ 3.50874981e-01,  5.21276833e-01, -1.37381950e+00],
       [-6.07689735e+00,  1.16576540e+00,  1.94784346e-01],
       [-1.29308785e+00,  8.46497303e-02,  1.30722764e+00],
       [-3.67325633e+00,  4.93414083e-01,  2.13376894e-01],
       [ 1.12892081e+00, -1.00877649e+00,  8.89914677e-01],
       [ 1.75383121e+00, -5.71243818e-02, -4.06225461e-01],
       [ 5.56787007e+00,  5.93956395e-01, -1.09100681e+00],
       [ 7.30421590e-01, -2.93790820e+00,  2.21708597e+00],
       [ 4.07880110e+00,  8.10897163e-01, -3.26960996e+00],
       [-3.83821167e-01,  1.47609826e+00, -9.62624936e-01],
       [-5.33153302e+00,  3.50648235e-01,  1.85878418e-01],
       [-9.43988578e-01,  1.06735666e+00, -8.92046959e-01],
       [-3.15884507e+00,  4.82103815e-01, -9.87894451e-01],
       [-3.68670904e+00, -5.59947703e-01, -9.15065099e-01],
       [-1.33101225e+00,  2.06115645e+00, -8.85912304e-01],
       [-1.67928229e+00,  8.81343131e-01,  3.31149704e-01],
       [ 1.66046198e+00, -7.75212079e-01, -8.84749547e-01],
       [ 1.37373056e+00,  5.86992027e-01, -1.08200268e+00],
       [ 5.28963205e+00,  7.23962303e-01, -3.36465481e+00],
       [-2.55387453e-01, -1.85823603e-01,  1.49270048e+00],
       [-1.92883368e+00,  5.03537126e-01,  2.59932325e-01],
       [-1.76050066e+00,  3.07823574e-01,  4.12722036e-01],
       [ 8.37293735e-01, -2.44676539e-01, -9.56786073e-01],
       [ 3.33147022e+00, -2.01399105e+00,  4.30934369e+00],
       [-2.47954938e+00,  1.32993246e+00, -1.46723940e+00],
       [ 1.16636928e+00,  2.01854943e-01, -1.55177274e+00],
       [-8.45063935e+00,  2.36075539e+00,  1.64290724e+00],
       [ 4.75240091e+00, -2.19105261e+00,  2.58896803e+00],
       [-1.14386307e+00,  1.18224656e+00,  3.73981770e-01],
       [-6.88237212e+00,  1.48075288e+00, -2.23278797e-01],
       [-1.63204188e+00,  7.33034137e-01, -3.83850393e-02],
       [-1.49983215e+00,  1.45973717e+00,  1.45526272e+00],
       [ 3.33341324e-01,  1.84729615e-01,  1.90920086e-02],
       [-5.47235687e+00,  1.41385211e+00,  5.91238781e-02],
       [-4.76547739e+00,  1.80254317e+00, -8.34193643e-01],
       [-1.85563011e+00,  4.96636991e-01, -2.03010856e-01],
       [-3.42931878e+00,  1.75756810e-01,  1.21800048e+00],
       [-5.67046984e+00, -7.64448081e-02, -1.12604184e-01],
       [ 3.98991886e+00,  1.68013377e+00, -2.40971653e+00],
       [ 5.03316057e+00,  1.43889948e+00, -4.11666661e-01],
       [-4.40366707e+00,  8.08064544e-01,  1.71745789e-01],
       [-1.83642975e-01,  2.05332774e+00, -1.08204252e+00],
       [-3.55323983e+00,  1.24739620e+00, -1.30417978e+00],
       [ 2.35712004e+00,  9.25067062e-01, -1.62465758e+00],
       [ 1.93438932e+00,  8.48359543e-01, -1.75545780e+00],
       [ 1.00599962e-01,  2.19840211e-02,  1.88451143e+00],
       [ 2.45423101e+00,  8.11903976e-01, -1.38397343e+00],
       [-2.71280763e+00,  8.23879871e-01, -1.23886933e+00],
       [-2.51278517e+00, -4.21689387e-01, -1.87876312e+00],
       [-5.47689507e+00,  8.50460581e-01,  1.13521873e-01],
       [-9.78188165e-01,  8.36280240e-01,  7.84723788e-02],
       [-3.98696744e+00,  1.15462634e+00, -2.03464435e-01],
       [-3.84872649e+00,  1.75264313e+00, -3.79654308e-04],
       [-1.28855377e+00, -2.53386566e-01,  1.79574685e+00],
       [ 3.49359177e+00,  5.24979316e-01, -2.45888977e-01],
       [ 2.47558865e+00,  1.15643706e+00, -1.53167493e+00],
       [ 2.53416459e+00, -4.06648949e+00, -1.82520118e-01],
       [-8.78619488e-01,  1.42994337e+00, -8.31885701e-01],
       [-5.44705851e+00,  1.61621947e+00,  7.89994224e-01],
       [-1.63107954e+00, -1.22725868e+00,  9.87792732e-01],
       [ 2.27126394e+00,  6.38540457e-01, -1.12258585e+00],
       [-3.73938357e-01,  1.40780784e+00, -7.28204891e-01],
       [-5.32851623e+00, -2.00688831e+00, -4.20188706e-01],
       [ 1.22981733e+00,  3.01006534e+00,  3.17634230e-01],
       [-4.62866938e+00,  8.79440599e-01,  2.11156724e-01],
       [-3.71433344e+00,  9.29553743e-01,  4.64907851e-01],
       [-4.58854981e+00,  7.91960332e-01,  4.13064291e-01],
       [-5.11531726e+00,  1.44481315e+00, -5.78857923e-01],
       [-2.38234989e-01, -1.58220467e+00, -2.38200893e+00],
       [ 1.12259874e+00,  7.98753564e-01, -2.73815779e+00],
       [ 2.15946746e+00,  1.02955833e+00, -1.21969066e+00],
       [ 6.82164731e-01, -6.41577942e-01,  8.56184185e-01],
       [ 2.71805106e-01, -1.26390269e+00,  1.35256143e+00],
       [-7.25095898e-01, -2.82980651e+00,  2.27820954e+00],
       [-7.66201879e+00,  7.97018120e-01,  5.29387114e-01],
       [-3.13743862e+00,  5.00025479e-01, -9.68132882e-01]])

In [21]:
pca.explained_variance_

array([10.73517123,  4.366842  ,  3.35248313])

In [22]:
len(pca.feature_names_in_)

228

## Converting array into dataframe

In [23]:
X_pca = pd.DataFrame(xtrain_pca)
X_pca

           0         1         2
0  -5.220714  1.040053  0.502247
1  -2.966836 -0.951353 -0.369779
2   1.570778  1.020898 -0.873816
3   0.350875  0.521277 -1.373819
4  -6.076897  1.165765  0.194784
..       ...       ...       ...
74  0.682165 -0.641578  0.856184
75  0.271805 -1.263903  1.352561
76 -0.725096 -2.829807  2.278210
77 -7.662019  0.797018  0.529387
78 -3.137439  0.500025 -0.968133

[79 rows x 3 columns]

In [24]:
X_pca.columns = ['PC1','PC2','PC3']
X_pca

         PC1       PC2       PC3
0  -5.220714  1.040053  0.502247
1  -2.966836 -0.951353 -0.369779
2   1.570778  1.020898 -0.873816
3   0.350875  0.521277 -1.373819
4  -6.076897  1.165765  0.194784
..       ...       ...       ...
74  0.682165 -0.641578  0.856184
75  0.271805 -1.263903  1.352561
76 -0.725096 -2.829807  2.278210
77 -7.662019  0.797018  0.529387
78 -3.137439  0.500025 -0.968133

[79 rows x 3 columns]

In [27]:

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=50,
                              max_depth=5)
model.fit(X_pca,ytrain['Weight'])

RandomForestRegressor(max_depth=5, n_estimators=50)

In [28]:
model.score(X_pca,ytrain)

0.9810757993166963

In [29]:

Xtest_pca = pca.transform(xtest_pre)
Xtest_pca

array([[-3.283607  ,  0.96192644, -1.23065928],
       [ 1.6872721 ,  2.70354686,  0.63860399],
       [-0.90080867,  1.26301524,  0.37099043],
       [ 3.0169872 ,  2.51177111,  0.19643244],
       [ 4.16154457,  0.8337048 , -3.68539536],
       [-7.30267374,  1.78008705,  1.41685593],
       [-2.56907182, -0.44425959, -1.65865534],
       [-0.48805361, -5.00129431, -0.06191056],
       [ 4.40388892, -2.21438563,  2.06700311],
       [-3.17040937, -1.88499334,  0.86067873],
       [-0.48967288, -1.46795743, -2.7119363 ],
       [ 1.99566871,  0.56480982,  2.4717596 ],
       [ 0.94894162,  0.72044024, -0.71206066],
       [ 1.98999397, -0.32641126,  2.03829325]])

In [30]:
Xtest_pca = pd.DataFrame(Xtest_pca)
Xtest_pca.columns = ['PC1','PC2','PC3']

In [31]:
model.score(Xtest_pca,ytest)

0.8766629042378341